# Generated by Django 5.1.3 on 2024-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
                ('category_img', models.ImageField(upload_to='category_pic')),
                ('product_total', models.IntegerField()),
            ],
        ),
    ]
